name: voice_message_package
description: Flutter package to play/puase voice message in chat messengers.
version: 2.2.1
homepage: https://mehran.monster/

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  audioplayers: ^6.1.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  syncfusion_flutter_sliders: ^28.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
